# Generated by Django 3.2.5 on 2022-02-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_pro',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Question_pro',
            new_name='Question',
        ),
    ]
