# Generated by Django 3.2.5 on 2022-02-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_subject', models.CharField(max_length=50)),
                ('Q_content', models.TextField()),
                ('Q_author', models.CharField(max_length=20)),
                ('Q_current_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_content', models.TextField()),
                ('A_author', models.CharField(max_length=20)),
                ('A_current_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probbs.question')),
            ],
        ),
    ]
