# Generated by Django 3.2.5 on 2022-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
