# Generated by Django 3.2.5 on 2022-03-02 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('probbs', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_like_count',
            field=models.ManyToManyField(related_name='like_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
